# Yggdrasil API 根地址
# 对于某 "统一"通行证,
# 他的地址是 https://auth2.nide8.com:233/{id}/
yggdrasil: "https://yggdrasil.example.com/"
# 检测玩家登录状态的时候先访问官方源
official-first: false
# 代理服务器端口
# 填 0 以自动分配
# 填 50000~51000
# 自动从 50000~51000中选择一个端口
port: 4321

# 代理读取超时时间(毫秒)
timed-out:
  reading: 60000
  connecting: 60000
# 链接代理
proxy:
  official:
    # direct 直接链接
    # socks  Socks代理
    # http   HTTP 代理
    type: "direct"
    host: "localhost"
    port: 1080
  yggdrasil:
    type: "direct"
extension:
  # 是否为MySkin之类的插件提供缺省地址修复
  yggdrasil-fix: true
  opts:
    injector:
      # 请替换成你自己的injector所在位置
      path: "G:/Java/authlib-injector-1.1.26-41a7a47.jar"
      # 没有需要的话不用改
      arg: "{proxy}"

